#!/bin/sh


#    Copyright (c) 2005 Brocade Communications Systems, Inc.
#    All rights reserved.
#
#    Description:
#     	Platform specific install script. 
#

/sbin/flash_write -i /mnt/boot/bootsel.bin -o /dev/bootsel
